auth_enabled: false

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /loki            # ← was common.path

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:                  # ← was common.storage.filesystem.*
  filesystem:
    directory: /loki/chunks

ruler:
  rule_path: /loki/rules
  storage:
    type: local
    local:
      directory: /loki/rules
  alertmanager_url: http://localhost:9093
